### PR TITLE
Fixed error: cut() is Undefined

### PR DESCRIPTION
**Pull request by eirikbrandsaas**
I guess there is something deeper going on with changing functionality in `DataFrames.jl` but at least this works on my system (Julia 1.5.0)

Edit: I  guess I should have opened this as an issue first instead of a pull request, but oh well.

### CODE REVIEW

**Comment by matthieugomez** [comment]
Thanks. I have pushed a fix — can you check the dev version works for you now? If so, I'll tag a new version with the fix.

**Comment by eirikbrandsaas** [comment]
0.1.3 works for me now. Thanks!

**Comment by matthieugomez** [comment]
Thanks for opening an issue about It! Let me know if you have other feedback.

**Comment by eirikbrandsaas** [comment]
Could it be that your fix doesn't correctly sort the bins again? And potentially ensure that the color of the line and bullets are the same when using `:scatterpath` (see picture for both issues).
Screenshot from 2021-04-07 08-08-22

**Comment by matthieugomez** [comment]
Hi Eirik, 
Thanks for your report. I'll try to fix it, but it'd be helpful to have a reproductible way of getting your graph.

**Comment by eirikbrandsaas** [comment]
Yes, sorry my bad!

```
N = 100
x = rand(N)
e = rand(N)
y = x+ e
df = DataFrame(y=y,x=X)
binscatter(df,@formula(y ~ x),seriestype=:scatterpath)
```
Yields 
Screenshot from 2021-04-07 16-11-08

What's going on is presumably that when you're finding quantiles the data is not sorted in ascending order.

**Comment by matthieugomez** [comment]
Thanks. Sorting works now, but color still does not match by default — the reason is that I simply use the formula `scatterpath` defined in Plots, and it does not match colors by default. You can specify the color yourself using `linecolor` `markercolor`, i.e. :
```julia
N = 100
x = rand(N)
e = rand(N)
y = x+ e
df = DataFrame(y=y,x=x)
binscatter(df,@formula(y ~ x),seriestype=:scatterpath, linecolor = :blue, markercolor = :blue)
```

**Comment by matthieugomez** [comment]
For reference, https://github.com/JuliaPlots/Plots.jl/issues/1495

**Comment by matthieugomez** [comment]
with Plots 1.12, `scatterpath` gives the same color for dots and lines.

**Pull request closed without merging**
